### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by fmatter**
Various fixes and additional features I've been meaning to incorporate for a while.

### CODE REVIEW

**Comment by xrotwang** [comment]
Does this require also updated data or can it be deployed with the current database?

**Comment by fmatter** [comment]
I’ve also made substantial updates to the CLDF database.


On 27 November 2020 at 16:07:57, Robert Forkel (notifications@github.com)
wrote:

Does this require also updated data or can it be deployed with the current
database?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/clld/cariban/pull/4#issuecomment-734877797>, or
unsubscribe

**Comment by xrotwang** [comment]
ok. so I'll pull this, too.

**Comment by xrotwang** [comment]
@fmatter can we fix this: https://github.com/cldf-datasets/mattercariban/issues/11

**Comment by fmatter** [comment]
> @fmatter can we fix this: [cldf-datasets/mattercariban#11](https://github.com/cldf-datasets/mattercariban/issues/11)

Fixed.

**Pull request merged**
